module.exports = {
  generator: "Generated by [rdm(1)](https://github.com/freeformsystems/rdm).",
  title: null,
  gfm: true,
  period: '.',
  pedantic: false,
  includes: null,
  require: null,
  branch: 'master',
  links: null,
  toc: false,
  order: false,
  base: null,
  partial: null
}
