module.exports = {
  generator: "Generated by [mdp(1)](https://github.com/tmpfs/mdp).",
  title: null,
  gfm: true,
  period: '.',
  pedantic: false,
  include: null,
  require: null,
  branch: 'master',
  links: null,
  toc: false,
  order: false,
  base: null,
  hash: false,
  level: 2,
  partial: null,
  env: false
}
